server:
  port: 8083
jwt:
  keys:
    private-key: |-
      -----BEGIN PRIVATE KEY-----
      MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgPGJGAm4X1fvBuC1z
      SpO/4Izx6PXfNMaiKaS5RUkFqEGhRANCAARCBvmeksd3QGTrVs2eMrrfa7CYF+sX
      sjyGg+Bo5mPKGH4Gs8M7oIvoP9pb/I85tdebtKlmiCZHAZE5w4DfJSV6
      -----END PRIVATE KEY-----
    #openssl ecparam -genkey -name prime256v1 -noout -out private.pem
    public-key: |-
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQgb5npLHd0Bk61bNnjK632uwmBfr
      F7I8hoPgaOZjyhh+BrPDO6CL6D/aW/yPObXXm7SpZogmRwGROcOA3yUleg==
      -----END PUBLIC KEY-----
    #openssl ec -in private.pem -pubout -out public.pem
    basic-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQgb5npLHd0Bk61bNnjK632uwmBfrF7I8hoPgaOZjyhh+BrPDO6CL6D/aW/yPObXXm7SpZogmRwGROcOA3yUleg==
    #Просто для базовой секьюрки, потом обязательно переделывается
  access-lifetime: 1h #10m optimal for production
  refresh-lifetime: 60d
spring:
  application:
    name: igodating-user-service
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
    url: jdbc:postgresql://localhost:5432/igodating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: igodating_user
        dialect: org.hibernate.dialect.PostgreSQLDialect