server:
  port: 9000

spring:
  cloud:
    openfeign:
      client:
        config:
          textEmbeddingService.url: http://localhost:5000/api/v1/
  application:
    name: igodating-questionary-service
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
    url: jdbc:postgresql://localhost:5432/igodating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        default_schema: igodating_questionary
        dialect: org.hibernate.dialect.PostgreSQLDialect

task:
  user-questionary-embedding-calculation-task:
    cron: 0 0/1 * * * ?
    batch-size: 100

recommendation:
  similarity-calculating-operator: EUCLID